name: Storybook Reminder

on:
  pull_request:
    paths:
      - '**.js'
      # - '**.stories.js'
    # types: opened

jobs:
  storybook_comment:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout
    - uses: thollander/actions-comment-pull-request@master
      with:
        message: Test comment
        # GITHUB_TOKEN: ${{ github.token }}
