name: Deploy Storybook Test

on:
  pull_request:
    paths:
      - '**.stories.js'
    # types: opened

jobs:
  deploy_storybook:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        clean: false
    - name: Run npm install
      run: npm install
    - name: Build Storybook
      run: npm run build-storybook -- --output-dir=.storybook-dist/${{ github['event']['pull_request']['number'] }}
    - name: Move files
      run: |
        mv .storybook-dist/${{ github['event']['pull_request']['number'] }}/* .
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Foreman Storybook Bot"
        git add .
        git status
        git commit -m "Storybook build for PR #${{ github['event']['pull_request']['number'] }}"
    - name: Deploy Storybook
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
        branch: gh-pages
    - name: Comment PR with new Storybook location
      uses: thollander/actions-comment-pull-request@master
      with:
        message: "See the Storybook for this PR: jeremylenz.github.io/foreman/.storybook-dist/${{ github['event']['pull_request']['number'] }}"
        GITHUB_TOKEN: ${{ github.token }}
