name: Storybook Reminder

on:
  pull_request:
    paths:
      - 'webpack/assets/javascripts/react_app/components'
      # - '**.stories.js'
    # types: opened

jobs:
  storybook_comment:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout
    - uses: thollander/actions-comment-pull-request@master
      with:
        message: Looks like some React files have changed.  If you've added or modified React components, don't forget to update the Storybook!
        GITHUB_TOKEN: ${{ github.token }}
