name: Storybook Reminder

on:
  pull_request:
    paths-ignore:
      - '**.stories.js'
    # types: opened

jobs:
  storybook_reminder:

    runs-on: ubuntu-latest

    steps:
    - name: Get Changed Files
      id: get_changed
      uses: lots0logs/gh-action-get-changed-files@2.0.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    # - uses: actions/checkout@v2
    #   name: Checkout
    - uses: thollander/actions-comment-pull-request@master
      name: Comment PR with Storybook reminder
    # if the list of changed files contains react_app, comment the PR
      if: contains(join(steps.get_changed.outputs.all), 'react_app')
      with:
        message: Looks like some React files have changed.  If you've added or modified React components, don't forget to update the Storybook!
        GITHUB_TOKEN: ${{ github.token }}
